trigger:
  branches:
    include:
      - main
      - trigger

variables:
  - group: PoC
  
pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: First
    jobs:
      - job: "First"
        displayName: "First Job in First Stage"
        steps:
          - checkout: self

          - task: PowerShell@2
            name: FirstJob
            displayName: "First "
            inputs:
              targetType: inline
              workingDirectory: "$(Build.SourcesDirectory)/"
              script: |              
                echo "Hi this 2nd task in First job of first step"
                echo "Variables: $(var1) $(var2)"

  - stage: Two
    dependsOn: First
    jobs:
      - deployment: "Two"
        environment: this-env-needs-approval
        displayName: "First Job in stage Two"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: PowerShell@2
                  name: JobTwo
                  displayName: "Get the version name for LeapDNA.Custom.Utilities"
                  inputs:
                    targetType: inline
                    script: |          
                      echo "Second Stage First Job First step"

  - stage: Publish
    dependsOn: Two
    jobs:
      - job: "Publish_Artifact"
        displayName: "Publish to Artifact Feed"
        steps:
          - checkout: self

          - task: UniversalPackages@0
            displayName: 'Universal publish'
            inputs:
              command: publish
              vstsFeedPublish: '$(feedname)'
              publishDirectory: '$(Build.SourcesDirectory)/publish'
              versionOption: Next patch
